// Env is declared globally by worker-configuration.d.ts (generated by `wrangler types`).
// Bindings come from wrangler.jsonc, secrets from .env / `wrangler secret put`.
// Create a .env file with the secrets listed in .env.example,
// then run `pnpm cf-typegen` to regenerate the Env interface.

// KV value stored under github:{github_id} and discord:{discord_id}
export interface LinkRecord {
	github_id: number;
	github_login: string;
	discord_id: string;
	discord_username: string;
	linked_at: string;
}

// Discord interaction types (subset)
export interface DiscordInteraction {
	type: number;
	token: string;
	id: string;
	application_id: string;
	guild_id?: string;
	member?: {
		user: {
			id: string;
			username: string;
			global_name?: string;
		};
		roles: string[];
	};
	data?: {
		name: string;
		custom_id?: string;
		component_type?: number;
	};
}

// GitHub webhook pull_request payload (subset)
export interface GitHubPRPayload {
	action: string;
	number: number;
	pull_request: {
		merged: boolean;
		title: string;
		html_url: string;
		user: {
			login: string;
			id: number;
		};
	};
	repository: {
		full_name: string;
	};
}
