import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, describe, expect, it } from "vitest";

import { checkDoctor, checkSchedulerWiring } from "../../../src/cli/commands/doctor.js";

const temporaryDirectories: string[] = [];

async function createSite(
	config: string,
	worker: string | null,
	configName = "wrangler.jsonc",
): Promise<string> {
	const cwd = await mkdtemp(join(tmpdir(), "emdash-doctor-"));
	temporaryDirectories.push(cwd);
	await mkdir(join(cwd, "src"));
	await writeFile(join(cwd, configName), config);
	if (worker !== null) await writeFile(join(cwd, "src/worker.ts"), worker);
	return cwd;
}

afterEach(async () => {
	await Promise.all(
		temporaryDirectories
			.splice(0)
			.map((directory) => rm(directory, { recursive: true, force: true })),
	);
});

describe("doctor scheduler wiring", () => {
	it("does not require Cloudflare scheduler wiring for a Node site", async () => {
		const cwd = await mkdtemp(join(tmpdir(), "emdash-doctor-node-"));
		temporaryDirectories.push(cwd);

		await expect(checkSchedulerWiring(cwd)).resolves.toEqual([]);
	});

	it("fails when a Cron Trigger points at a Worker without scheduled maintenance", async () => {
		const cwd = await createSite(
			`{
				"main": "./src/worker.ts",
				"triggers": { "crons": ["* * * * *"] },
			}`,
			`import handler from "@astrojs/cloudflare/entrypoints/server";
			export default handler;`,
		);

		const results = await checkSchedulerWiring(cwd);

		expect(results).toEqual([
			expect.objectContaining({
				name: "scheduler handler",
				status: "fail",
			}),
		]);
		expect(results[0]!.message).toContain("Cron Trigger is configured");
		expect(results[0]!.message).toContain(
			'export { default, PluginBridge } from "@emdash-cms/cloudflare/worker";',
		);
	});

	it("fails when an EmDash Worker has no Cron Trigger", async () => {
		const cwd = await createSite(
			`{
				// The Worker entry is wired, but scheduling is not.
				"main": "./src/worker.ts",
			}`,
			`export { default, PluginBridge } from "@emdash-cms/cloudflare/worker";`,
		);

		const results = await checkSchedulerWiring(cwd);

		expect(results).toEqual([
			expect.objectContaining({
				name: "scheduler trigger",
				status: "fail",
			}),
		]);
		expect(results[0]!.message).toContain("scheduled() handler is exported");
		expect(results[0]!.message).toContain('"crons": ["* * * * *"]');
	});

	it("passes for a Worker with both scheduler pieces", async () => {
		const cwd = await createSite(
			`{
				"main": "./src/worker.ts",
				"triggers": {
					"crons": ["* * * * *"],
				},
			}`,
			`export { default, PluginBridge } from "@emdash-cms/cloudflare/worker";`,
		);

		await expect(checkSchedulerWiring(cwd)).resolves.toEqual([
			expect.objectContaining({
				name: "scheduler wiring",
				status: "pass",
			}),
		]);
	});

	it("accepts the custom Worker form generated by current templates", async () => {
		const cwd = await createSite(
			`{
				"main": "./src/worker.ts",
				"triggers": { "crons": ["* * * * *", "*/2 * * * *"] },
			}`,
			`import handler, { createScheduledHandler, PluginBridge } from "@emdash-cms/cloudflare/worker";
			export { PluginBridge };
			export default { ...handler, scheduled: createScheduledHandler() };`,
		);

		await expect(checkSchedulerWiring(cwd)).resolves.toEqual([
			expect.objectContaining({ status: "pass" }),
		]);
	});

	it("supports Wrangler TOML configurations", async () => {
		const cwd = await createSite(
			`main = "./src/worker.ts"

			[triggers]
			crons = ["* * * * *"]`,
			`export { default, PluginBridge } from "@emdash-cms/cloudflare/worker";`,
			"wrangler.toml",
		);

		await expect(checkSchedulerWiring(cwd)).resolves.toEqual([
			expect.objectContaining({ name: "scheduler wiring", status: "pass" }),
		]);
	});

	it("provides a TOML Cron Trigger fix for a TOML Worker configuration", async () => {
		const cwd = await createSite(
			`main = "./src/worker.ts"`,
			`export { default, PluginBridge } from "@emdash-cms/cloudflare/worker";`,
			"wrangler.toml",
		);

		const [result] = await checkSchedulerWiring(cwd);

		expect(result).toMatchObject({ name: "scheduler trigger", status: "fail" });
		expect(result!.message).toContain('[triggers]\ncrons = ["* * * * *"]');
		expect(result!.message).not.toContain('"triggers":');
	});

	it("does not treat an unrelated Worker without scheduler pieces as broken wiring", async () => {
		const cwd = await createSite(
			`{ "main": "./src/worker.ts" }`,
			`import handler from "@astrojs/cloudflare/entrypoints/server";
			export default handler;`,
		);

		await expect(checkSchedulerWiring(cwd)).resolves.toEqual([]);
	});

	it("keeps database checks additive for a Cloudflare deployment", async () => {
		const cwd = await createSite(
			`{
				"main": "./src/worker.ts",
				"d1_databases": [{ "binding": "DB", "database_name": "site" }],
				"triggers": { "crons": ["* * * * *"] },
			}`,
			`export { default, PluginBridge } from "@emdash-cms/cloudflare/worker";`,
		);

		const results = await checkDoctor(cwd, join(cwd, "data.db"));

		expect(results).toContainEqual(expect.objectContaining({ name: "database", status: "fail" }));
		expect(results).toContainEqual(
			expect.objectContaining({ name: "scheduler wiring", status: "pass" }),
		);
	});

	it("keeps the local database check for a Node deployment", async () => {
		const cwd = await mkdtemp(join(tmpdir(), "emdash-doctor-node-"));
		temporaryDirectories.push(cwd);

		const results = await checkDoctor(cwd, join(cwd, "missing.db"));

		expect(results).toContainEqual(expect.objectContaining({ name: "database", status: "fail" }));
	});

	it("reports invalid Wrangler JSONC with a source location", async () => {
		const cwd = await createSite(
			`{
				"main": "./src/worker.ts",
				"triggers": { "crons": ["* * * * *"]
				BROKEN
			}`,
			`export { default, PluginBridge } from "@emdash-cms/cloudflare/worker";`,
		);

		const [result] = await checkSchedulerWiring(cwd);

		expect(result).toMatchObject({ name: "scheduler config", status: "fail" });
		expect(result!.message).toMatch(/line \d+, column \d+/);
	});

	it("reports a missing Worker main entry", async () => {
		const cwd = await createSite(`{ "triggers": { "crons": ["* * * * *"] } }`, null);

		const [result] = await checkSchedulerWiring(cwd);

		expect(result).toMatchObject({ name: "scheduler handler", status: "fail" });
		expect(result!.message).toContain('add "main": "./src/worker.ts"');
	});

	it("provides a TOML main entry fix for a TOML configuration", async () => {
		const cwd = await createSite(`[triggers]\ncrons = ["* * * * *"]`, null, "wrangler.toml");

		const [result] = await checkSchedulerWiring(cwd);

		expect(result!.message).toContain('add main = "./src/worker.ts"');
		expect(result!.message).not.toContain('"main":');
	});

	it("reports a missing Worker entry file", async () => {
		const cwd = await createSite(
			`{ "main": "./src/worker.ts", "triggers": { "crons": ["* * * * *"] } }`,
			null,
		);

		const [result] = await checkSchedulerWiring(cwd);

		expect(result!.message).toContain("Worker entry not found");
	});

	it("distinguishes unreadable Worker entries from missing files", async () => {
		const cwd = await createSite(
			`{ "main": "./src", "triggers": { "crons": ["* * * * *"] } }`,
			`export default {};`,
		);

		const [result] = await checkSchedulerWiring(cwd);

		expect(result!.message).toContain("could not read Worker entry");
		expect(result!.message).not.toContain("not found");
	});
});
