/**
 * Workers Cache (native Workers Caching) status + purge handlers.
 *
 * Uses `cache.purge()` from `cloudflare:workers` via the
 * `virtual:emdash/workers-cache` module (same platform API as wrangler
 * `"cache": { "enabled": true }` / Astro `cacheCloudflare()`).
 * No zone ID or Cache Purge API token.
 *
 * Safe when the API is missing (Node, older runtimes, cache not enabled):
 * status reports `configured: false` and purge is a no-op success.
 */

import type { ApiResult } from "../types.js";

export interface WorkersCacheStatus {
	/** Whether native `cache.purge` is available in this runtime. */
	configured: boolean;
}

export interface WorkersCachePurgeInput {
	/**
	 * Path prefixes to invalidate (e.g. `/posts/hello`). Omit or pass empty
	 * to purge everything for this Worker entrypoint.
	 */
	pathPrefixes?: string[];
}

export interface WorkersCachePurgeResult {
	/** Whether native `cache.purge` was available. */
	configured: boolean;
	/** True when purge ran and reported success. */
	purged: boolean;
	/** Path prefixes that were purged (empty when purge-everything). */
	pathPrefixes?: string[];
}

export interface WorkersCachePurgeApi {
	purge(options: {
		purgeEverything?: boolean;
		tags?: string[];
		pathPrefixes?: string[];
	}): Promise<unknown>;
}

/** Matches an absolute URL scheme prefix (e.g. `https://`). */
const ABSOLUTE_URL_RE = /^[a-zA-Z][a-zA-Z+\-.]*:\/\//;

/**
 * Normalize a user-supplied path or full URL into a Workers Caching path prefix.
 * Strips origin, query, and hash; ensures a leading slash.
 */
export function normalizeWorkersCachePathPrefix(
	raw: string,
): { ok: true; path: string } | { ok: false; message: string } {
	const trimmed = raw.trim();
	if (!trimmed) {
		return { ok: false, message: "Path is required" };
	}

	let path: string;
	if (ABSOLUTE_URL_RE.test(trimmed)) {
		try {
			const url = new URL(trimmed);
			path = url.pathname || "/";
		} catch {
			return { ok: false, message: "Invalid URL" };
		}
	} else {
		// Strip query/hash if pasted without a scheme
		const withoutHash = trimmed.split("#")[0] ?? trimmed;
		const withoutQuery = withoutHash.split("?")[0] ?? withoutHash;
		path = withoutQuery;
	}

	if (!path.startsWith("/")) {
		path = `/${path}`;
	}

	// Collapse duplicate slashes except we keep a single leading /
	path = path.replace(/\/{2,}/g, "/");

	if (path.length > 2048) {
		return { ok: false, message: "Path is too long" };
	}

	return { ok: true, path };
}

/**
 * Resolve the native Workers Caching purge API.
 * Injected in tests; at runtime loads `virtual:emdash/workers-cache`.
 */
export async function resolveWorkersCachePurgeApi(
	override?: WorkersCachePurgeApi | null,
): Promise<WorkersCachePurgeApi | null> {
	if (override !== undefined) return override;

	try {
		// @ts-ignore - virtual module, generated by the Astro integration
		const mod = (await import("virtual:emdash/workers-cache")) as {
			cache?: WorkersCachePurgeApi;
		};
		const cache = mod.cache;
		if (cache && typeof cache.purge === "function") {
			return {
				purge: (options) => cache.purge(options),
			};
		}
	} catch {
		// Virtual module unavailable outside Vite/Astro
	}
	return null;
}

/**
 * Report whether native Workers Cache purge is available.
 */
export async function handleWorkersCacheStatus(
	api?: WorkersCachePurgeApi | null,
): Promise<ApiResult<WorkersCacheStatus>> {
	try {
		const resolved = api === undefined ? await resolveWorkersCachePurgeApi() : api;
		return { success: true, data: { configured: resolved !== null } };
	} catch {
		return {
			success: false,
			error: {
				code: "WORKERS_CACHE_STATUS_ERROR",
				message: "Failed to read Workers Cache status",
			},
		};
	}
}

/**
 * Purge Workers Caching for this entrypoint.
 * With `pathPrefixes`, purges those prefixes; otherwise `purgeEverything`.
 */
export async function handleWorkersCachePurge(
	input: WorkersCachePurgeInput = {},
	api?: WorkersCachePurgeApi | null,
): Promise<ApiResult<WorkersCachePurgeResult>> {
	try {
		const resolved = api === undefined ? await resolveWorkersCachePurgeApi() : api;

		if (!resolved) {
			return {
				success: true,
				data: { configured: false, purged: false },
			};
		}

		const rawPrefixes = input.pathPrefixes ?? [];
		const normalized: string[] = [];
		const seen = new Set<string>();

		for (const raw of rawPrefixes) {
			if (typeof raw !== "string") {
				return {
					success: false,
					error: {
						code: "VALIDATION_ERROR",
						message: "Each path prefix must be a string",
					},
				};
			}
			const result = normalizeWorkersCachePathPrefix(raw);
			if (!result.ok) {
				return {
					success: false,
					error: {
						code: "VALIDATION_ERROR",
						message: result.message,
					},
				};
			}
			if (!seen.has(result.path)) {
				seen.add(result.path);
				normalized.push(result.path);
			}
		}

		const purgeOptions =
			normalized.length > 0 ? { pathPrefixes: normalized } : { purgeEverything: true as const };

		const result = await resolved.purge(purgeOptions);

		if (isPurgeFailure(result)) {
			const detail = formatPurgeErrors(result);
			return {
				success: false,
				error: {
					code: "WORKERS_CACHE_PURGE_ERROR",
					message: detail ? `Workers Cache purge failed: ${detail}` : "Workers Cache purge failed",
				},
			};
		}

		return {
			success: true,
			data: {
				configured: true,
				purged: true,
				...(normalized.length > 0 ? { pathPrefixes: normalized } : {}),
			},
		};
	} catch (error) {
		const message = error instanceof Error ? error.message : "Unknown error";
		return {
			success: false,
			error: {
				code: "WORKERS_CACHE_PURGE_ERROR",
				message: `Failed to purge Workers Cache: ${message}`,
			},
		};
	}
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null;
}

function isPurgeFailure(value: unknown): boolean {
	if (!isRecord(value) || typeof value.success !== "boolean") {
		// Unknown shape — treat as success (older/no-result APIs)
		return false;
	}
	return value.success === false;
}

function formatPurgeErrors(value: unknown): string | undefined {
	if (!isRecord(value) || !Array.isArray(value.errors)) return undefined;
	const messages = value.errors
		.map((error) => {
			if (isRecord(error) && typeof error.message === "string") return error.message;
			return String(error);
		})
		.filter(Boolean);
	return messages.length > 0 ? messages.join("; ") : undefined;
}
